### ISSUE TITLE
Show list of PHPStrom version and intall it

### ISSUE THREAD

**Issue by devlubinets** [nagygergo/jetbrains-toolbox-install#20]
I think it was good thing to fast install phpstorm ide

**Comment by linghengqian** [comment]
- I don't think this is what this git should consider.  I feel jetbrains should first consider exposing more parameters for its AppImage, this kind of thing should be discussed on youtrack.

**Comment by nagygergo** [comment]
Yes, this is a very small scoped script, there are number of gists for automating those things, like this: https://gist.github.com/ankurk91/7688d80d3d3071473c6fd8d4b1a20f5e
