### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by rpearcy4791** [nagygergo/jetbrains-toolbox-install#3]
Is there a way to use this to uninstall everything that was installed?

Thanks

**Comment by nagygergo** [comment]
As I see, toolbox itself provides a way to remove the installed tools on its own GUI. 

Toolbox itself can be removed by clearing the symlink: `rm /usr/local/bin/jetbrains-toolbox`
Then remove the folder: `rm -r -f /opt/jetbrains-toolbox`

Sorry for the very very late answer. Probably you figured it out, but good for future reference
