### ISSUE TITLE
Jetbrains-toolbox - having issues running on Pi4

### ISSUE THREAD

**Issue by wyantj** [nagygergo/jetbrains-toolbox-install#7]
Looking for some help, suggestions etc.
I have a Pi 4 8 gig, running Raspbian GNU/Linux 10 (buster).
Getting the error below from jetbrains-toolbox. 
I installed via, **sudo bash jetbrains-toolbox.sh**

/usr/local/bin/jetbrains-toolbox: line 2: /opt/jetbrains-toolbox/jetbrains-toolbox: cannot execute binary file: Exec format error

**Comment by AureliuT** [comment]
I have the same problem :(
